language: minimal

addons:
  apt:
    packages:
    - curl


env:
  global:
    - TARGET=x86_64-unknown-linux-gnu
    - CUDA_ROOT="$HOME/cuda"
    - PATH="$HOME/.cargo/bin:$PATH"
  matrix:
    - CUDA=80 RUST=stable
    - CUDA=91 RUST=stable
    - CUDA=80 RUST=beta
    - CUDA=91 RUST=beta
    - CUDA=80 RUST=nightly
    - CUDA=91 RUST=nightly

before_install:
  - ci/before_install.sh

install:
  - ci/install.sh

script:
  - ci/script.sh

after_script: true

cache: cargo

branches:
  only:
    - auto
    - master
    - try

notifications:
  email:
on_success: never